version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb

    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp/sockets
      - log-data:/webapp/log/nginx
    depends_on:
      - db
    # networks: 
    #   - webapp-network
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql


  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp/sockets
    ports:
      - 80:80
    depends_on:
      - app
    # networks:
    #   - webapp-network

volumes:
  public-data:
  tmp-data:
    driver: local 
  log-data:
  db-data:
    driver: local

# networks:
#   webapp-network:
#     external: true



